export const demographicsArray: { value: string }[] = [
  { value: "Impaired Hearing" },
  { value: "Impaired vision" },
  { value: "LBTQI+" },
  { value: "Bisexual" },
  { value: "Transgender" },
  { value: "Gay" },
  { value: "HIV/AIDS" },
  { value: "Sex positive" },
  { value: "Queer" },
  { value: "Lesbian" },
  { value: "Latinx" },
  { value: "Black Community" },
  { value: "POC" },
  { value: "Ex-Felons" },
  { value: "Senior Community" },
  { value: "Physically Disabled" },
  { value: "Open relationship/Non-monogamy" },
  { value: "Dwarfism" },
  { value: "Native American Community" },
  { value: "Asian Community" },
  { value: "Military Combat Veterans" },
  { value: "Asian Community" },
  { value: "Immigrants" },
  { value: "Refugees" },
]
