export const issuesArray: { value: string }[] = [
  { value: "Depression" },
  { value: "Anxiety" },
  { value: "Life transition" },
  { value: "Grief" },
  { value: "Divorce" },
  { value: "Abuse" },
  { value: "ADHD" },
  { value: "Anger" },
  { value: "Personality Disorders" },
  { value: "Mood Disorders" },
  { value: "Relationship Issues" },
  { value: "Family Issues" },
  { value: "Autism Spectrum Disorder" },
  { value: "Guilt" },
  { value: "HIV/AIDS" },
  { value: "Body Image" },
  { value: "Identity Issues" },
  { value: "Isolation" },
  { value: "Chronic Pain" },
  { value: "Midlife Crisis" },
  { value: "Mood Swings" },
  { value: "Drug and Alcohol Addiction" },
  { value: "Performance Anxiety" },
  { value: "Phobias" },
  { value: "Life purpose" },
  { value: "Gender Dysphoria" },
  { value: "LGBTQI+ Issues" },
  { value: "Stress" },
  { value: "Suicide" },
  { value: "Self-Esteem Issues" },
  { value: "Self-Injury" },
  { value: "Self-Doubt" },
  { value: "Spirituality" },
  { value: "Self-Care" },
  { value: "Burnout" },
  { value: "Bullying" },
  { value: "Fertility Issues" },
  { value: "Trauma" },
  { value: "Young Adult Issues" },
  { value: "Burnout" },
  { value: "POC Issues" },
]
