export const languagesArray: { value: string }[] = [
  { value: "English" },
  { value: "Spanish" },
  { value: "French" },
  { value: "Japanese" },
  { value: "Korean" },
  { value: "Hindi" },
  { value: "Arabic" },
  { value: "German" },
  { value: "Polish" },
  { value: "Dutch" },
  { value: "Portuguese" },
  { value: "Italian" },
  { value: "Mandarin" },
  { value: "Russian" },
  { value: "Filipino" },
  { value: "Bengali" },
  { value: "Yoruba" },
  { value: "Igbo" },
  { value: "Greek" },
  { value: "Czech" },
]
