export const modalitiesArray: { value: string }[] = [
  { value: "EMDR" },
  { value: "CBT" },
  { value: "ACT" },
  { value: "Art Therapy" },
  { value: "Behavioral Therapy" },
  { value: "DBT" },
  { value: "Brief Psychotherapy" },
  { value: "Cient-Centered Therapy" },
  { value: "CFT" },
  { value: "Drama Therapy" },
  { value: "EFT" },
  { value: "Existential Therapy" },
  { value: "Gestalt Therapy" },
  { value: "Holistic Therapy" },
  { value: "Humanistic Therapy" },
  { value: "Hypnotherapy" },
  { value: "Existential Therapy" },
  { value: "Logotherapy" },
  { value: "Junguian Therapy" },
  { value: "Motivational Interviewing" },
  { value: "Music Therapy" },
  { value: "Narrative Therapy" },
  { value: "Object Relations Therapy" },
  { value: "Play Therapy" },
  { value: "Narrative Therapy" },
  { value: "Psychoanalysis" },
  { value: "Psychodrama" },
  { value: "Narrative Therapy" },
  { value: "Schema Therapy" },
  { value: "Structural Therapy" },
  { value: "TRU" },
  { value: "Animal-Assisted Therapy" },
  { value: "Psychodynamic Therapy" },
  { value: "Positive Psychology" },
  { value: "Feminist Therapy" },
  { value: "Sandplay Therapy" },
  { value: "Mindfulness-Based Cognitive Therapy" },
  { value: "Compassion-Focused Therapy" },
  { value: "Cognitive Therapy" },
  { value: "Somatic Experiencing" },
  { value: "Grief Therapy" },
  { value: "Life Transitions Therapy" },
  { value: "Alderian Psychotherapy" },
  { value: "Brainspotting" },
  { value: "Dance/Movement Therapy" },
  { value: "Ecotherapy" },
  { value: "Neuropsychlogy" },
  { value: "Reichian Therapy" },
  { value: "Transference-focused Therapy" },
]
